import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import NextTopLoader from 'nextjs-toploader';
const clash = localFont({
  src: [
    {
      path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Bold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Extralight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Light.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Regular.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Semibold.otf",
      weight: "700",
      style: "normal",
    },
  ],

  variable: "--font-clash",
});

const satoshi = localFont({
  src: [
    {
      path: "./fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Medium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Bold.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Black.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi_Complete/Fonts/OTF/Satoshi-BlackItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Regular.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
       
         <NextTopLoader color="bg-blue" height={18}/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
