import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const clash = localFont({src: [
  
  {
    path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Bold.otf",
    weight: "800",
    style: "normal",
  },
  {
    path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Extralight.otf",
    weight: "300",
    style: "normal",
  },
  {
    path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Light.otf",
    weight: "400",
    style: "normal",
  },
  {
    path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Medium.otf",
    weight: "500",
    style: "normal",
  },
  {
    path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Regular.otf",
    weight: "600",
    style: "normal",
  },
  {
    path: "./fonts/ClashDisplay_Complete/Fonts/OTF/ClashDisplay-Semibold.otf",
    weight: "700",
    style: "normal",
  }],
  variable: "--font-clash",
}

)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${clash.variable} antialiased bg-white text-black`}
      >
        {children}
      </body>
    </html>
  );
}
